# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install npm dependencies
      run: npm install
    - name: change the config
      run: echo "export const settings = { host:\"http://localhost:3030" }" > config.js
    - name: Start the backend
      run: npm run start-be &
    - name: Start the frontEnd
      run: npm run start-fe &
    - name: Install playwight browser
      run: npx playwright install 
    - name: Start the Ui tests
      run: npm run test:ui
  deploy_backend_render:
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/main'
   needs: build_and_test
   steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.BACKEND_API_KEY }}
          api_key: ${{ secrets.RENDER_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          wait_deploy: true 
  
  deploy_frontend_render:
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/main'
   needs: deploy_backend_render
   steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.FRONTEND_API_KEY }}
          api_key: ${{ secrets.RENDER_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          wait_deploy: true 
